### ISSUE TITLE
ルビ使用時の文字色の変更について

### ISSUE THREAD

**Issue by ken5-4rasawa** [publictheta/vscode-japanese-novel#1]
ルビ表記を使用する場合にオレンジに変える機能がありますが、
字下げを行った場合に通常文字色に戻ってしまうのは仕様でしょうか

**Comment by publictheta** [comment]
手元の環境で確認しましたが、全角スペース（`　`、U+3000）での字下げを行ったとき、

- テキストファイル（`.txt`、言語モード「小説」）では正しく表示される
- Markdownファイル（`.md`、言語モード「Markdown」）ではシンタックスハイライト（文字色の変更等）がすべて消えてしまう

という状態になっていました。言語モードが「小説（`japanese-novel`）」になっていても発生するようであれば、サンプルテキストをいただけるとありがたいです。

Markdownであれば「小説」拡張機能を無効にしてみても同じ事象が確認できたため、おそらくVS Code本体組み込みのMarkdown機能の仕様かバグだと思います。

```md
 __test__  // 太字になる
　__test__ // 太字にならない
```

（↑の全角スペースはGitHub上でも半角スペースの倍の幅になっていないかもしれません。）

よろしければVS Code本体のリポジトリのほうを確認して必要であればイシューを立ててみようと思いますが、少し時間がかかると思います。

「小説」拡張機能はテキストファイルについてはいちから実装していますが、MarkdownについてはVS Code組み込みの機能にルビ構文の拡張を追加するだけの部分的なサポートになっています。

他のMarkdownの機能を使わなくてもいいのであれば、言語モードを「小説（`japanese-novel`）」にすることで字下げも正しく行われると思うので、よろしければお試しください。デフォルトでは`.txt`が「小説」ファイルとして認識されるようになっているので、拡張子を`.txt`に変えるだけで有効になるはずです。

また、VS Codeではファイル拡張子と言語モードの結びつきを設定で上書きすることもできるので、独自の拡張子や既存の拡張子に「小説（`japanese-novel`）」を結びつけることもできます。

基本設定 > 「`files.associations`」で検索 >

- 独自の拡張子
    - 項目: `*.novel`
    - 値: `japanese-novel`
- 既存の拡張子
    - 項目: `*.md`
    - 値: `japanese-novel`

設定はワークスペース単位で行うこともできるので、小説用のワークスペースでだけこの設定を有効にすることもできます。

（ご報告ありがとうございます。自分一人だとどうしても使い方が偏ってしまうのでとても助かります。）

**Comment by ken5-4rasawa** [comment]
ご回答ありがとうございます
小説モードにした所正しく色設定が行われました

.txt形式で言語モードがMarkdownだったために着色が正しく行われなかったものと理解しました
別の拡張機能のFormat NovelとCharactorCountを併用しているため想定していない組み合わせでの使い方になったものと思います。
ありがとうございます
