### ISSUE TITLE
一部の文字を太字にしたい

### ISSUE THREAD

**Issue by stIprurIJu** [publictheta/vscode-japanese-novel#2]
見出しの文字を太字にしたいのですが、その機能はありませんか？

**Comment by publictheta** [comment]
ご質問ありがとうございます。返答が遅くなってしまい申し訳ありません。

現時点では、プレーンテキスト形式（`.txt`）について、一般的な小説投稿サイトの互換性を重視しつつ機能をシンプルに保つ方針で開発しているため、ルビと傍点のみに対応しており、太字を含むそれ以外の装飾には対応しておりません。

将来的には、例えば青空文庫形式の注記に対応するというような方針をとることも可能性としてはありますが、かなり大規模な改修が必要となるため、開発と維持にかかるコストとの兼ね合いから、当面は予定しておりません。

また、別の方針としては、VS Codeの標準機能であるMarkdown形式（`.md`）についての拡充を行うということも考えられ、こちらはごく簡単な対応を現時点でも行ってはいるのですが、こちらもこれ以上の機能の追加については、内部の処理との複雑な連携が必要となるため、すぐに行うのは難しいというのが現状です。

あまりご期待に添えない回答となってしまい申し訳ありませんが、今後も気軽にご質問いただければと思います。

**Comment by stIprurIJu** [comment]
了解です。
もうWordよりこちらの方が使い易いな～と思っていたので、残念ですが仕方ないですね。
ありがとう御座いました。
