### ISSUE TITLE
傍点の位置がズレる

### ISSUE THREAD

**Issue by stIprurIJu** [publictheta/vscode-japanese-novel#3]
傍点を付けたのですが、位置がズレてしまいます。
修正をお願い致します。
![image](https://github.com/publictheta/vscode-japanese-novel/assets/164626763/a9003b1e-998b-4fb4-8274-6220b21c5b01)

**Comment by publictheta** [comment]
ご報告ありがとうございます。画像も添えていただき、大変助かります。

当方の環境でも同じ問題を確認できましたので、新しいバージョン（0.1.9）にて、修正を行いました。

VS Codeおよび当拡張機能を最新版にアップデートしていただいた上で、ご確認いただけますと幸いです。

それでも不具合が解消されていない場合は、お手数ですが再度ご報告ください（こちらにコメントしていただく形で結構です）。

私個人では問題を把握しきれないことが多いので、すぐに対応できるとは限りませんが、今後とも気軽にご報告ください。

**Comment by stIprurIJu** [comment]
直りました。ご対応、ありがとう御座います。
